name: mercure-totalsegmentator
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dcm2niix
  - pydicom
  - jupyterlab
  - pip
  - pip :
    - scikit-learn 
    - TotalSegmentator
    - typeguard~=2.12.1 # Work around MONAI requirements.txt bug that picks up the wrong typeguard version
    - highdicom
    - rt-utils
    - torch>=1.12.0
    - monai>=1.0.0
    - monai-deploy-app-sdk==0.5.0

